"""add user discriminators

Revision ID: 0a1c62edb1bf
Revises: 67a6c8885b0c
Create Date: 2020-06-18 22:19:08.620670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a1c62edb1bf'
down_revision = '67a6c8885b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('discriminator', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'discriminator')
    # ### end Alembic commands ###
