"""rename macro_responses and macro_reactions to custom_*

Revision ID: 18b24c92d541
Revises: 76110e69ef78
Create Date: 2020-05-16 21:03:50.924214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b24c92d541'
down_revision = '76110e69ef78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('macro_reactions', 'custom_reactions')
    op.rename_table('macro_responses', 'custom_responses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('custom_reactions', 'macro_reactions')
    op.rename_table('custom_responses', 'macro_responses')
    # ### end Alembic commands ###
