"""add guild_id to commands/responses/reactions

Revision ID: 194413c16e68
Revises: aaeee2ef2d88
Create Date: 2020-06-05 01:04:13.833096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194413c16e68'
down_revision = 'aaeee2ef2d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_commands', sa.Column('guild_id', sa.BigInteger(), nullable=True))
    op.create_index('ix_custom_command_unique_guild_command', 'custom_commands', ['guild_id', 'command'], unique=True, postgresql_where=sa.text('command IS NOT NULL'))
    op.create_index('ix_custom_command_unique_guild_name', 'custom_commands', ['guild_id', 'name'], unique=True, postgresql_where=sa.text('name IS NOT NULL'))
    op.drop_constraint('custom_commands_command_key', 'custom_commands', type_='unique')
    op.drop_constraint('uq_custom_commands_name', 'custom_commands', type_='unique')
    op.create_foreign_key(None, 'custom_commands', 'guilds', ['guild_id'], ['id'])
    op.add_column('custom_reactions', sa.Column('guild_id', sa.BigInteger(), nullable=True))
    op.create_index('ix_custom_reaction_unique_guild_name', 'custom_reactions', ['guild_id', 'name'], unique=True, postgresql_where=sa.text('name IS NOT NULL'))
    op.create_index('ix_custom_reaction_unique_guild_trigger', 'custom_reactions', ['guild_id', 'trigger'], unique=True, postgresql_where=sa.text('trigger IS NOT NULL'))
    op.drop_constraint('custom_reactions_trigger_key', 'custom_reactions', type_='unique')
    op.drop_constraint('uq_custom_reactions_name', 'custom_reactions', type_='unique')
    op.create_foreign_key(None, 'custom_reactions', 'guilds', ['guild_id'], ['id'])
    op.add_column('custom_responses', sa.Column('guild_id', sa.BigInteger(), nullable=True))
    op.create_index('ix_custom_response_guild_trigger', 'custom_responses', ['guild_id', 'trigger'], unique=True, postgresql_where=sa.text('trigger IS NOT NULL'))
    op.create_index('ix_custom_response_unique_guild_name', 'custom_responses', ['guild_id', 'name'], unique=True, postgresql_where=sa.text('name IS NOT NULL'))
    op.drop_constraint('custom_responses_trigger_key', 'custom_responses', type_='unique')
    op.drop_constraint('uq_custom_responses_name', 'custom_responses', type_='unique')
    op.create_foreign_key(None, 'custom_responses', 'guilds', ['guild_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'custom_responses', type_='foreignkey')
    op.create_unique_constraint('uq_custom_responses_name', 'custom_responses', ['name'])
    op.create_unique_constraint('custom_responses_trigger_key', 'custom_responses', ['trigger'])
    op.drop_index('ix_custom_response_unique_guild_name', table_name='custom_responses')
    op.drop_index('ix_custom_response_guild_trigger', table_name='custom_responses')
    op.drop_column('custom_responses', 'guild_id')
    op.drop_constraint(None, 'custom_reactions', type_='foreignkey')
    op.create_unique_constraint('uq_custom_reactions_name', 'custom_reactions', ['name'])
    op.create_unique_constraint('custom_reactions_trigger_key', 'custom_reactions', ['trigger'])
    op.drop_index('ix_custom_reaction_unique_guild_trigger', table_name='custom_reactions')
    op.drop_index('ix_custom_reaction_unique_guild_name', table_name='custom_reactions')
    op.drop_column('custom_reactions', 'guild_id')
    op.drop_constraint(None, 'custom_commands', type_='foreignkey')
    op.create_unique_constraint('uq_custom_commands_name', 'custom_commands', ['name'])
    op.create_unique_constraint('custom_commands_command_key', 'custom_commands', ['command'])
    op.drop_index('ix_custom_command_unique_guild_name', table_name='custom_commands')
    op.drop_index('ix_custom_command_unique_guild_command', table_name='custom_commands')
    op.drop_column('custom_commands', 'guild_id')
    # ### end Alembic commands ###
