"""add column for guildmembership roles

Revision ID: 1c0e676f4a4e
Revises: 0a1c62edb1bf
Create Date: 2020-06-18 23:08:35.523088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1c0e676f4a4e'
down_revision = '0a1c62edb1bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_membership', sa.Column('roles', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_membership', 'roles')
    # ### end Alembic commands ###
