"""add user_filter to response/reaction

Revision ID: 2c031400c83b
Revises: 194413c16e68
Create Date: 2020-06-15 17:08:45.123752

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c031400c83b'
down_revision = '194413c16e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_commands', sa.Column('user_filter', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.add_column('custom_reactions', sa.Column('user_filter', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.add_column('custom_responses', sa.Column('user_filter', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_responses', 'user_filter')
    op.drop_column('custom_reactions', 'user_filter')
    op.drop_column('custom_commands', 'user_filter')
    # ### end Alembic commands ###
