"""add role filter

Revision ID: 6312d3d7dbb3
Revises: 1c0e676f4a4e
Create Date: 2020-06-21 21:40:10.109182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6312d3d7dbb3'
down_revision = '1c0e676f4a4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_commands', sa.Column('role_filter', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.add_column('custom_reactions', sa.Column('role_filter', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    op.add_column('custom_responses', sa.Column('role_filter', postgresql.ARRAY(sa.String()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_responses', 'role_filter')
    op.drop_column('custom_reactions', 'role_filter')
    op.drop_column('custom_commands', 'role_filter')
    # ### end Alembic commands ###
