"""normalize command/response/reaction variable names

Revision ID: 67a6c8885b0c
Revises: 2c031400c83b
Create Date: 2020-06-17 14:00:19.192488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a6c8885b0c'
down_revision = '2c031400c83b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_custom_command_unique_guild_command', table_name='custom_commands')
    op.alter_column('custom_commands', 'command', new_column_name='trigger')
    op.create_index('ix_custom_command_unique_guild_command', 'custom_commands', ['guild_id', 'trigger'], unique=True, postgresql_where=sa.text('trigger IS NOT NULL'))

    op.alter_column('custom_reactions', 'reaction', new_column_name='response')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('custom_reactions', 'reaction', new_column_name='reaction')

    op.drop_index('ix_custom_command_unique_guild_command', table_name='custom_commands')
    op.alter_column('custom_commands', 'trigger', new_column_name='command')
    op.create_index('ix_custom_command_unique_guild_command', 'custom_commands', ['guild_id', 'command'], unique=True)
    # ### end Alembic commands ###
