"""add command/response/reaction cooldowns

Revision ID: aaeee2ef2d88
Revises: ee4ac7eb67cc
Create Date: 2020-05-28 21:29:24.139460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaeee2ef2d88'
down_revision = 'ee4ac7eb67cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_commands', sa.Column('cooldown', sa.Boolean(), nullable=True))
    op.add_column('custom_commands', sa.Column('cooldown_bucket', sa.Integer(), nullable=True))
    op.add_column('custom_commands', sa.Column('cooldown_per', sa.Float(), nullable=True))
    op.add_column('custom_commands', sa.Column('cooldown_rate', sa.Integer(), nullable=True))
    op.add_column('custom_commands', sa.Column('cooldown_multiplier', sa.Integer(), nullable=True))
    op.add_column('custom_reactions', sa.Column('cooldown', sa.Boolean(), nullable=True))
    op.add_column('custom_reactions', sa.Column('cooldown_bucket', sa.Integer(), nullable=True))
    op.add_column('custom_reactions', sa.Column('cooldown_per', sa.Float(), nullable=True))
    op.add_column('custom_reactions', sa.Column('cooldown_rate', sa.Integer(), nullable=True))
    op.add_column('custom_reactions', sa.Column('cooldown_multiplier', sa.Integer(), nullable=True))
    op.add_column('custom_responses', sa.Column('cooldown', sa.Boolean(), nullable=True))
    op.add_column('custom_responses', sa.Column('cooldown_bucket', sa.Integer(), nullable=True))
    op.add_column('custom_responses', sa.Column('cooldown_per', sa.Float(), nullable=True))
    op.add_column('custom_responses', sa.Column('cooldown_rate', sa.Integer(), nullable=True))
    op.add_column('custom_responses', sa.Column('cooldown_multiplier', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_responses', 'cooldown_multiplier')
    op.drop_column('custom_responses', 'cooldown_rate')
    op.drop_column('custom_responses', 'cooldown_per')
    op.drop_column('custom_responses', 'cooldown_bucket')
    op.drop_column('custom_responses', 'cooldown')
    op.drop_column('custom_reactions', 'cooldown_multiplier')
    op.drop_column('custom_reactions', 'cooldown_rate')
    op.drop_column('custom_reactions', 'cooldown_per')
    op.drop_column('custom_reactions', 'cooldown_bucket')
    op.drop_column('custom_reactions', 'cooldown')
    op.drop_column('custom_commands', 'cooldown_multiplier')
    op.drop_column('custom_commands', 'cooldown_rate')
    op.drop_column('custom_commands', 'cooldown_per')
    op.drop_column('custom_commands', 'cooldown_bucket')
    op.drop_column('custom_commands', 'cooldown')
    # ### end Alembic commands ###
