"""add name/description/regex/multi_response to commands/responses/reactions

Revision ID: ee4ac7eb67cc
Revises: 786387e0de51
Create Date: 2020-05-22 00:09:41.458256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee4ac7eb67cc'
down_revision = '786387e0de51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_commands', sa.Column('description', sa.String(), nullable=True))
    op.add_column('custom_commands', sa.Column('multi_response', sa.Boolean(), nullable=True))
    op.add_column('custom_commands', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('custom_commands', 'modified_flag')
    op.create_unique_constraint('uq_custom_commands_name', 'custom_commands', ['name'])
    op.add_column('custom_reactions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('custom_reactions', sa.Column('multi_response', sa.Boolean(), nullable=True))
    op.add_column('custom_reactions', sa.Column('name', sa.String(), nullable=True))
    op.add_column('custom_reactions', sa.Column('use_regex', sa.Boolean(), nullable=True))
    op.create_unique_constraint('uq_custom_reactions_name', 'custom_reactions', ['name'])
    op.add_column('custom_responses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('custom_responses', sa.Column('multi_response', sa.Boolean(), nullable=True))
    op.add_column('custom_responses', sa.Column('name', sa.String(), nullable=True))
    op.add_column('custom_responses', sa.Column('use_regex', sa.Boolean(), nullable=True))
    op.create_unique_constraint('uq_custom_responses_name', 'custom_responses', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_custom_commands_name', 'custom_commands', type_='unique')
    op.drop_column('custom_commands', 'name')
    op.drop_column('custom_commands', 'multi_response')
    op.drop_column('custom_commands', 'description')
    op.add_column('custom_commands', sa.Column('modified_flag', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_custom_responses_name', 'custom_responses', type_='unique')
    op.drop_column('custom_responses', 'use_regex')
    op.drop_column('custom_responses', 'name')
    op.drop_column('custom_responses', 'multi_response')
    op.drop_column('custom_responses', 'description')
    op.drop_constraint('uq_custom_reactions_name', 'custom_reactions', type_='unique')
    op.drop_column('custom_reactions', 'use_regex')
    op.drop_column('custom_reactions', 'name')
    op.drop_column('custom_reactions', 'multi_response')
    op.drop_column('custom_reactions', 'description')


    # ### end Alembic commands ###
