version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(name)s - %(levelname)s - %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    discord:
        level: NOTSET
        handlers: []
        propagate: no

    cleo:
        level: DEBUG
        handlers: [error_file_handler, console]
        propagate: no
    app:
        level: INFO
        handlers: [error_file_handler]
        propagate: no
root:
    level: INFO
    handlers: [console]
